print('What do you get when you cross a snowman with a vampire?')
input()
print('Frosbites!')
print()
print('what do dentists call a astronout\'s cavity?')
input()
print('A black hole')
print()
print('Knock knock')
input()
print("who's there?")
input()
print('Interrupting cow wh', end='') # this will not make newline so wh-MOO! is printed (by end='')
print('-MOO!')